{
    "name": "Food Ordering System",
    "summary": "Guest food ordering, cashier/kitchen workflow, own-cup discounts and print queues",
    "author": "Local Food Ordering Project",
    "version": "19.0.10.0.0",
    "category": "Sales/Food Ordering",
    "license": "LGPL-3",
    "depends": ["website_sale", "sale_management"],
    "data": [
        "security/food_ordering_security.xml",
        "security/ir.model.access.csv",
        "data/food_ordering_data.xml",
        "data/food_department_data.xml",
        "data/food_menu_categories.xml",
        "data/food_starter_menu.xml",
        "data/food_nepali_menu.xml",
        "data/food_product_images.xml",
        "data/food_modifier_data.xml",
        "views/food_order_views.xml",
        "views/product_views.xml",
        "views/food_menu_category_views.xml",
        "views/food_modifier_views.xml",
        "views/food_department_views.xml",
        "views/food_print_views.xml",
        "views/food_payment_views.xml",
        "views/food_promotion_views.xml",
        "views/food_device_pairing_views.xml",
        "views/food_staff_templates.xml",
        "views/website_templates.xml",
        "views/food_pwa_head.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "food_ordering/static/src/css/food_ordering.css",
            "food_ordering/static/src/css/food_staff.css",
            "food_ordering/static/src/js/food_ordering.js",
            "food_ordering/static/src/js/food_staff.js",
        ],
    },
    "external_dependencies": {"python": ["qrcode"]},
    "application": True,
    "installable": True,
}
